"""Preserve known native engine defaults in a temporary web build overlay."""

import ast
import os
import re
import shutil
from pathlib import Path


_SHIM_NAME = "_vnm_legacy_search_prefixes.rpy"
_SHIM = '''# Generated by VNoctis for engines with the legacy images/ fallback.
# Run before ordinary game init, allowing game settings to override this default.
init -999 python:
    if config.search_prefixes == [""]:
        config.search_prefixes = ["", "images/"]
'''


def needs_legacy_image_lookup(game_path: str) -> bool:
    """Read a literal engine default without executing imported Python code.

    Older engines may contain Python 2 syntax, so parsing the entire module
    with Python 3 is unsuitable. Unknown or dynamic defaults are left alone.
    """
    config = Path(game_path) / "renpy" / "config.py"
    if not config.is_file():
        return False
    match = re.search(
        r"^search_prefixes\s*=\s*(\[[^\]]*\])[^\S\n]*(?:#[^\n]*)?$",
        config.read_text(encoding="utf-8", errors="replace"),
        re.MULTILINE,
    )
    if not match:
        return False
    try:
        return ast.literal_eval(match.group(1)) == ["", "images/"]
    except (ValueError, SyntaxError):
        return False


def create_uncompressed_overlay(game_path: str, overlay_path: str) -> None:
    """Link assets into a disposable build tree, including real directories."""
    source = Path(game_path).resolve()
    overlay = Path(overlay_path)
    if overlay.exists():
        shutil.rmtree(overlay)
    for root, _, files in os.walk(source):
        destination = overlay / Path(root).relative_to(source)
        destination.mkdir(parents=True, exist_ok=True)
        for name in files:
            (destination / name).symlink_to(Path(root) / name)


def prepare_build_overlay(overlay_path: str, legacy_image_lookup: bool) -> None:
    """Keep compiler outputs/settings local and optionally install the shim."""
    overlay = Path(overlay_path)
    # The SDK can recompile scripts. Do not let its writes follow links back
    # into the imported game, with or without asset compression enabled.
    for root, _, files in os.walk(overlay):
        for name in files:
            path = Path(root) / name
            if path.is_symlink() and (
                path.suffix.lower() in {".rpy", ".rpyc", ".rpym", ".rpymc"}
                or path == overlay / "progressive_download.txt"
            ):
                source = path.resolve()
                path.unlink()
                shutil.copy2(source, path)
    if legacy_image_lookup:
        shim = overlay / "game" / _SHIM_NAME
        if shim.exists() or shim.with_suffix(".rpyc").exists():
            raise RuntimeError(f"Reserved compatibility script already exists: {shim.name}")
        shim.parent.mkdir(parents=True, exist_ok=True)
        shim.write_text(_SHIM, encoding="utf-8")
